### ISSUE TITLE
Limit maximum response size

### ISSUE THREAD

**Issue by pornel** [visionmedia/superagent#1259]
Superagent buffers and uncompresses responses in memory. Malicious server could send extremely large response causing superagent to use excessive amounts of memory.

I suggest adding a way to set a maximum response size, and have a default limit set.

**Comment by letsgolesco** [comment]
Heads up, this is blocking my company's CI builds - would appreciate a speedy fix if it's possible.

**Comment by pornel** [comment]
Could you help by making a pull request?

**Comment by walshie4** [comment]
I'm in to help, breaking our builds as well (for the time being @letsgolesco you can use a `.nsprc` file to ignore this advisory). I'll report back with any progress.

**Comment by westy92** [comment]
To ignore for now, add the following to an `.nsprc` file:
```json
{
  "exceptions": ["https://nodesecurity.io/advisories/479"]
}
```

**Comment by pornel** [comment]
Fixed in v3.7.0

**Comment by edmorley** [comment]
This is still showing on https://nodesecurity.io/advisories/479 as not fixed, so I've dropped them an email to update the advisory :-)

**Comment by chrisfosterelli** [comment]
It's updated now 🎉

**Comment by ir-fuel** [comment]
Can someone point me to where it is explained how to set a maximum response size? I would like to download more than 200MB, but I can't find how to specify a bigger number.

**Comment by Enet4** [comment]
In case someone stumbles upon this issue, the maximum response size can be changed via the method [`maxResponseSize`](https://github.com/visionmedia/superagent/commit/946e28dab08f2ab334753bf36a2fbc5110d17789#diff-be27821c599006faab0d29e2cace0392R423).

```javascript
superagent.get(url)
    .maxResponseSize(4000000000)
```
