### ISSUE TITLE
Zlib / incorrect header check in vanilla request

### ISSUE THREAD

**Issue by djechlin** [visionmedia/superagent#260]
My request looks like this:

	var req = request
		.get("https://apis.live.net/v5.0/me/contacts")
		.query({
		"access_token": accessToken
	}).end(function() { });

Seems to be enough to give this error:

    Error: incorrect header check
        at Zlib._binding.onerror (zlib.js:295:17)

When I build the URL myself with a valid access token and point my browser to it, the request succeeds.

**Comment by defunctzombie** [comment]
Closing due to age. I think zlib issues have been resolved in newer versions.

**Comment by jayceekay** [comment]
@defunctzombie i'm still seeing this. newer versions of what? superagent, zlib?

**Comment by landonpoch** [comment]
Should be re-opened.  I'm seeing this also.  I believe there are a couple of other bugs related to zlib not working: https://github.com/visionmedia/superagent/issues/927, https://github.com/danwrong/restler/issues/96

I did notice that I had to change my headers from:
`{ "Accept-Encoding": "gzip, deflate" }`
to this:
`{ "Accept-Encoding": "gzip" }`

That seemed to fix it.

**Comment by pornel** [comment]
Can you provide a complete example with a URL that reproduces this problem?

**Comment by walshie4** [comment]
Had been looking into #1283 when I happened upon this.  [My fork](https://github.com/walshie4/superagent/tree/zip-bomb) reproduces this issue (although I think I'm forcing it a bit).
